### PR TITLE
Fix switching diff algorithms

### LINKED ISSUE #768: Issues swapping between diff algorithms after changing it for the first time
After changing the diff algorithm, it starts to behave weirdly when trying to change it a 2nd time
This is on firefox 113.0.1
https://gyazo.com/66e5115dd98a76707c9d2feca68b1e2c

### PR DESCRIPTION
**Pull request by ConorBobbleHat**
Fixes #768.

Turns out both flags were being set at once, and given that Quantum Diffing (™️) still isn't stable, this PR fixes that.

### CODE REVIEW

**Review by ethteck — APPROVED** [review]

File: frontend/src/components/compiler/CompilerOpts.tsx [hunk 1]
```diff
@@ -63,17 +64,19 @@ function FlagSet({ name, children, value }) {
...
         <Select
             onChange={event => {
-                for (const child of children) {
-                    setFlag(child.props.flag, false)
-                }
+                const trueFlag = (event.target as HTMLSelectElement).value
 
-                setFlag((event.target as HTMLSelectElement).value, true)
+                const edits = children.map(child => {
+                    return { flag: child.props.flag, value: child.props.flag == trueFlag }
```
Comment (nanaian) [inline frontend/src/components/compiler/CompilerOpts.tsx:76]: I'm hesistant here because `DiffFlagSet`'s `children` arg isn't typed, but I guess pretty much none of this file is typed so its fine?

**Review by nanaian — COMMENTED** [review]
LGTM if we dont want to add typing

**Review by nanaian — APPROVED** [review]
ty!

**Comment by ConorBobbleHat** [comment]
np!
